// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: portal/order.proto

package mall

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据购物车信息生成确认单
type GenerateConfirmOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartIds []uint64 `protobuf:"varint,1,rep,packed,name=cart_ids,json=cartIds,proto3" json:"cart_ids,omitempty"`
}

func (x *GenerateConfirmOrderReq) Reset() {
	*x = GenerateConfirmOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderReq) ProtoMessage() {}

func (x *GenerateConfirmOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderReq.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateConfirmOrderReq) GetCartIds() []uint64 {
	if x != nil {
		return x.CartIds
	}
	return nil
}

type GenerateConfirmOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartPromotionItems        *GenerateConfirmOrderRsp_CartPromotionItem         `protobuf:"bytes,1,opt,name=cart_promotion_items,json=cartPromotionItems,proto3" json:"cart_promotion_items,omitempty"`                      // 包含优惠信息的购物车信息
	MemberReceiveAddress      *GenerateConfirmOrderRsp_MemberReceiveAddress      `protobuf:"bytes,2,opt,name=member_receive_address,json=memberReceiveAddress,proto3" json:"member_receive_address,omitempty"`                // 用户收货地址列表
	CouponHistoryDetails      *GenerateConfirmOrderRsp_CouponHistoryDetail       `protobuf:"bytes,3,opt,name=coupon_history_details,json=couponHistoryDetails,proto3" json:"coupon_history_details,omitempty"`                // 用户可用优惠券列表
	IntegrationConsumeSetting *GenerateConfirmOrderRsp_IntegrationConsumeSetting `protobuf:"bytes,4,opt,name=integration_consume_setting,json=integrationConsumeSetting,proto3" json:"integration_consume_setting,omitempty"` // 积分使用规则
	MemberIntegration         uint32                                             `protobuf:"varint,5,opt,name=member_integration,json=memberIntegration,proto3" json:"member_integration,omitempty"`                          // 会员持有的积分
	CalcAmount                *GenerateConfirmOrderRsp_CalcAmount                `protobuf:"bytes,6,opt,name=calc_amount,json=calcAmount,proto3" json:"calc_amount,omitempty"`                                                // 计算的金额
}

func (x *GenerateConfirmOrderRsp) Reset() {
	*x = GenerateConfirmOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateConfirmOrderRsp) GetCartPromotionItems() *GenerateConfirmOrderRsp_CartPromotionItem {
	if x != nil {
		return x.CartPromotionItems
	}
	return nil
}

func (x *GenerateConfirmOrderRsp) GetMemberReceiveAddress() *GenerateConfirmOrderRsp_MemberReceiveAddress {
	if x != nil {
		return x.MemberReceiveAddress
	}
	return nil
}

func (x *GenerateConfirmOrderRsp) GetCouponHistoryDetails() *GenerateConfirmOrderRsp_CouponHistoryDetail {
	if x != nil {
		return x.CouponHistoryDetails
	}
	return nil
}

func (x *GenerateConfirmOrderRsp) GetIntegrationConsumeSetting() *GenerateConfirmOrderRsp_IntegrationConsumeSetting {
	if x != nil {
		return x.IntegrationConsumeSetting
	}
	return nil
}

func (x *GenerateConfirmOrderRsp) GetMemberIntegration() uint32 {
	if x != nil {
		return x.MemberIntegration
	}
	return 0
}

func (x *GenerateConfirmOrderRsp) GetCalcAmount() *GenerateConfirmOrderRsp_CalcAmount {
	if x != nil {
		return x.CalcAmount
	}
	return nil
}

// 根据购物车信息生成订单
type GenerateOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberReceiveAddressId uint64   `protobuf:"varint,1,opt,name=member_receive_address_id,json=memberReceiveAddressId,proto3" json:"member_receive_address_id,omitempty"` // 收货地址ID
	CouponId               uint64   `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`                                               // 优惠券ID
	UseIntegration         uint32   `protobuf:"varint,3,opt,name=use_integration,json=useIntegration,proto3" json:"use_integration,omitempty"`                             // 使用的积分数
	PayType                uint32   `protobuf:"varint,4,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`                                                  // 支付方式
	CartIds                []uint64 `protobuf:"varint,5,rep,packed,name=cart_ids,json=cartIds,proto3" json:"cart_ids,omitempty"`                                           // 被选中的购物车商品ID
}

func (x *GenerateOrderReq) Reset() {
	*x = GenerateOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOrderReq) ProtoMessage() {}

func (x *GenerateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOrderReq.ProtoReflect.Descriptor instead.
func (*GenerateOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateOrderReq) GetMemberReceiveAddressId() uint64 {
	if x != nil {
		return x.MemberReceiveAddressId
	}
	return 0
}

func (x *GenerateOrderReq) GetCouponId() uint64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *GenerateOrderReq) GetUseIntegration() uint32 {
	if x != nil {
		return x.UseIntegration
	}
	return 0
}

func (x *GenerateOrderReq) GetPayType() uint32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *GenerateOrderReq) GetCartIds() []uint64 {
	if x != nil {
		return x.CartIds
	}
	return nil
}

type GenerateOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateOrderRsp) Reset() {
	*x = GenerateOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOrderRsp) ProtoMessage() {}

func (x *GenerateOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOrderRsp.ProtoReflect.Descriptor instead.
func (*GenerateOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{3}
}

// 用户支付成功的回调
type PaySuccessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaySuccessReq) Reset() {
	*x = PaySuccessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaySuccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySuccessReq) ProtoMessage() {}

func (x *PaySuccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySuccessReq.ProtoReflect.Descriptor instead.
func (*PaySuccessReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{4}
}

type PaySuccessRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaySuccessRsp) Reset() {
	*x = PaySuccessRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaySuccessRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaySuccessRsp) ProtoMessage() {}

func (x *PaySuccessRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaySuccessRsp.ProtoReflect.Descriptor instead.
func (*PaySuccessRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{5}
}

// 自动取消超时订单
type CancelTimeOutOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelTimeOutOrderReq) Reset() {
	*x = CancelTimeOutOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTimeOutOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTimeOutOrderReq) ProtoMessage() {}

func (x *CancelTimeOutOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTimeOutOrderReq.ProtoReflect.Descriptor instead.
func (*CancelTimeOutOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{6}
}

type CancelTimeOutOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelTimeOutOrderRsp) Reset() {
	*x = CancelTimeOutOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTimeOutOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTimeOutOrderRsp) ProtoMessage() {}

func (x *CancelTimeOutOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTimeOutOrderRsp.ProtoReflect.Descriptor instead.
func (*CancelTimeOutOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{7}
}

// 取消单个超时订单
type CancelOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{8}
}

type CancelOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelOrderRsp) Reset() {
	*x = CancelOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRsp) ProtoMessage() {}

func (x *CancelOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRsp.ProtoReflect.Descriptor instead.
func (*CancelOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{9}
}

// 按状态分页获取用户订单列表
type OrderListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{10}
}

type OrderListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderListRsp) Reset() {
	*x = OrderListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListRsp) ProtoMessage() {}

func (x *OrderListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListRsp.ProtoReflect.Descriptor instead.
func (*OrderListRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{11}
}

// 根据ID获取订单详情
type OrderDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *OrderDetailReq) Reset() {
	*x = OrderDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailReq) ProtoMessage() {}

func (x *OrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailReq.ProtoReflect.Descriptor instead.
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{12}
}

func (x *OrderDetailReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderDetailRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderDetailRsp) Reset() {
	*x = OrderDetailRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDetailRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailRsp) ProtoMessage() {}

func (x *OrderDetailRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailRsp.ProtoReflect.Descriptor instead.
func (*OrderDetailRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{13}
}

// 用户取消订单
type CancelUserOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelUserOrderReq) Reset() {
	*x = CancelUserOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelUserOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUserOrderReq) ProtoMessage() {}

func (x *CancelUserOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUserOrderReq.ProtoReflect.Descriptor instead.
func (*CancelUserOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{14}
}

type CancelUserOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelUserOrderRsp) Reset() {
	*x = CancelUserOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelUserOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUserOrderRsp) ProtoMessage() {}

func (x *CancelUserOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUserOrderRsp.ProtoReflect.Descriptor instead.
func (*CancelUserOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{15}
}

// 用户确认收货
type ConfirmReceiveOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmReceiveOrderReq) Reset() {
	*x = ConfirmReceiveOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReceiveOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceiveOrderReq) ProtoMessage() {}

func (x *ConfirmReceiveOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceiveOrderReq.ProtoReflect.Descriptor instead.
func (*ConfirmReceiveOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{16}
}

type ConfirmReceiveOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmReceiveOrderRsp) Reset() {
	*x = ConfirmReceiveOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmReceiveOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceiveOrderRsp) ProtoMessage() {}

func (x *ConfirmReceiveOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceiveOrderRsp.ProtoReflect.Descriptor instead.
func (*ConfirmReceiveOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{17}
}

// 用户删除订单
type DeleteOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOrderReq) Reset() {
	*x = DeleteOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderReq) ProtoMessage() {}

func (x *DeleteOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderReq.ProtoReflect.Descriptor instead.
func (*DeleteOrderReq) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{18}
}

type DeleteOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOrderRsp) Reset() {
	*x = DeleteOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRsp) ProtoMessage() {}

func (x *DeleteOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRsp.ProtoReflect.Descriptor instead.
func (*DeleteOrderRsp) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{19}
}

// 计算的金额
type GenerateConfirmOrderRsp_CalcAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmount     float64 `protobuf:"fixed64,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`             // 订单商品总金额
	FreightAmount   float64 `protobuf:"fixed64,2,opt,name=freight_amount,json=freightAmount,proto3" json:"freight_amount,omitempty"`       // 运费
	PromotionAmount float64 `protobuf:"fixed64,3,opt,name=promotion_amount,json=promotionAmount,proto3" json:"promotion_amount,omitempty"` // 活动优惠
	PayAmount       float64 `protobuf:"fixed64,4,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`                   // 应付金额
}

func (x *GenerateConfirmOrderRsp_CalcAmount) Reset() {
	*x = GenerateConfirmOrderRsp_CalcAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp_CalcAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp_CalcAmount) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp_CalcAmount) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp_CalcAmount.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp_CalcAmount) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GenerateConfirmOrderRsp_CalcAmount) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_CalcAmount) GetFreightAmount() float64 {
	if x != nil {
		return x.FreightAmount
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_CalcAmount) GetPromotionAmount() float64 {
	if x != nil {
		return x.PromotionAmount
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_CalcAmount) GetPayAmount() float64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

// 积分使用规则
type GenerateConfirmOrderRsp_IntegrationConsumeSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                               //
	DeductionPerAmount int32 `protobuf:"varint,2,opt,name=deduction_per_amount,json=deductionPerAmount,proto3" json:"deduction_per_amount,omitempty"`   // 每一元需要抵扣的积分数量
	MaxPercentPerOrder int32 `protobuf:"varint,3,opt,name=max_percent_per_order,json=maxPercentPerOrder,proto3" json:"max_percent_per_order,omitempty"` // 每笔订单最高抵用百分比
	UseUnit            int32 `protobuf:"varint,4,opt,name=use_unit,json=useUnit,proto3" json:"use_unit,omitempty"`                                      // 每次使用积分最小单位100
	CouponStatus       int32 `protobuf:"varint,5,opt,name=coupon_status,json=couponStatus,proto3" json:"coupon_status,omitempty"`                       // 是否可以和优惠券同用；0->不可以；1->可以
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) Reset() {
	*x = GenerateConfirmOrderRsp_IntegrationConsumeSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp_IntegrationConsumeSetting) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp_IntegrationConsumeSetting.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp_IntegrationConsumeSetting) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) GetDeductionPerAmount() int32 {
	if x != nil {
		return x.DeductionPerAmount
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) GetMaxPercentPerOrder() int32 {
	if x != nil {
		return x.MaxPercentPerOrder
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) GetUseUnit() int32 {
	if x != nil {
		return x.UseUnit
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_IntegrationConsumeSetting) GetCouponStatus() int32 {
	if x != nil {
		return x.CouponStatus
	}
	return 0
}

// 用户收货地址列表
type GenerateConfirmOrderRsp_MemberReceiveAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // ID
	MemberId      int64  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`                // 会员ID
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                         // 收货人名称
	PhoneNumber   string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`        // 电话号码
	DefaultStatus int32  `protobuf:"varint,5,opt,name=default_status,json=defaultStatus,proto3" json:"default_status,omitempty"` // 是否为默认
	PostCode      string `protobuf:"bytes,6,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`                 // 邮政编码
	Province      string `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`                                 // 省份/直辖市
	City          string `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`                                         // 城市
	Region        string `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`                                     // 区
	DetailAddress string `protobuf:"bytes,10,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"` // 详细地址(街道)
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) Reset() {
	*x = GenerateConfirmOrderRsp_MemberReceiveAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp_MemberReceiveAddress) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp_MemberReceiveAddress.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp_MemberReceiveAddress) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetDefaultStatus() int32 {
	if x != nil {
		return x.DefaultStatus
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_MemberReceiveAddress) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

// 购物车中促销信息的封装
type GenerateConfirmOrderRsp_CartPromotionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromotionMessage string `protobuf:"bytes,2,opt,name=promotion_message,json=promotionMessage,proto3" json:"promotion_message,omitempty"` // 促销活动信息
	ReduceAmount     string `protobuf:"bytes,3,opt,name=reduce_amount,json=reduceAmount,proto3" json:"reduce_amount,omitempty"`             // 促销活动减去的金额，针对每个商品
	RealStock        int32  `protobuf:"varint,4,opt,name=real_stock,json=realStock,proto3" json:"real_stock,omitempty"`                     // 剩余库存-锁定库存
	Integration      int32  `protobuf:"varint,5,opt,name=integration,proto3" json:"integration,omitempty"`                                  // 购买商品赠送积分
	Growth           int32  `protobuf:"varint,6,opt,name=growth,proto3" json:"growth,omitempty"`                                            // 购买商品赠送成长值
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) Reset() {
	*x = GenerateConfirmOrderRsp_CartPromotionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp_CartPromotionItem) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp_CartPromotionItem.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp_CartPromotionItem) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1, 3}
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) GetPromotionMessage() string {
	if x != nil {
		return x.PromotionMessage
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) GetReduceAmount() string {
	if x != nil {
		return x.ReduceAmount
	}
	return ""
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) GetRealStock() int32 {
	if x != nil {
		return x.RealStock
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) GetIntegration() int32 {
	if x != nil {
		return x.Integration
	}
	return 0
}

func (x *GenerateConfirmOrderRsp_CartPromotionItem) GetGrowth() int32 {
	if x != nil {
		return x.Growth
	}
	return 0
}

// 优惠券领取历史详情（包括优惠券信息和关联关系）
type GenerateConfirmOrderRsp_CouponHistoryDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateConfirmOrderRsp_CouponHistoryDetail) Reset() {
	*x = GenerateConfirmOrderRsp_CouponHistoryDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portal_order_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateConfirmOrderRsp_CouponHistoryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfirmOrderRsp_CouponHistoryDetail) ProtoMessage() {}

func (x *GenerateConfirmOrderRsp_CouponHistoryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_portal_order_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfirmOrderRsp_CouponHistoryDetail.ProtoReflect.Descriptor instead.
func (*GenerateConfirmOrderRsp_CouponHistoryDetail) Descriptor() ([]byte, []int) {
	return file_portal_order_proto_rawDescGZIP(), []int{1, 4}
}

var File_portal_order_proto protoreflect.FileDescriptor

var file_portal_order_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x13, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x23, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07,
	0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x73, 0x22, 0xc5, 0x0b, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x62, 0x0a, 0x14, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x12, 0x63, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x69, 0x0a, 0x16, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x14, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x68, 0x0a, 0x16, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x73, 0x70, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x14, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x78, 0x0a, 0x1b,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x38, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x19, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x12, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x11, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0xa0, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x66, 0x72, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x61, 0x79, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xd0, 0x01, 0x0a, 0x19, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x12, 0x64, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x12, 0x6d, 0x61, 0x78, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x50,
	0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x75, 0x73, 0x65, 0x55, 0x6e,
	0x69, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0xad, 0x02, 0x0a, 0x14, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0xbe, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x0a,
	0x11, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x20,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x1a, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0xfb, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x19, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x28, 0x00,
	0x52, 0x16, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x32, 0x02, 0x28, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30,
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x00,
	0x52, 0x0e, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x0b, 0xfa, 0x42, 0x08, 0x2a, 0x06, 0x30, 0x00, 0x30, 0x01, 0x30, 0x02, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x04, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92,
	0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x73, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x73, 0x70, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x17, 0x0a, 0x15,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x73, 0x70, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x14, 0x0a,
	0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x73, 0x70, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x32, 0x8e, 0x08, 0x0a, 0x0e,
	0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12, 0x7e,
	0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x3a, 0x01,
	0x2a, 0x22, 0x1b, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x62,
	0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22, 0x14, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x56, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x79, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x50,
	0x61, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x73, 0x70, 0x22, 0x1c, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x70, 0x61, 0x79, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x76, 0x0a, 0x12, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x24, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x5a, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22,
	0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4a,
	0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x5c, 0x0a, 0x0b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x73, 0x70, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12,
	0x17, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2f, 0x7b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x7d, 0x12, 0x6a, 0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x7a, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1f, 0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x5a, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x1d, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x3b, 0x6d, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portal_order_proto_rawDescOnce sync.Once
	file_portal_order_proto_rawDescData = file_portal_order_proto_rawDesc
)

func file_portal_order_proto_rawDescGZIP() []byte {
	file_portal_order_proto_rawDescOnce.Do(func() {
		file_portal_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_portal_order_proto_rawDescData)
	})
	return file_portal_order_proto_rawDescData
}

var file_portal_order_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_portal_order_proto_goTypes = []interface{}{
	(*GenerateConfirmOrderReq)(nil),                           // 0: admin.GenerateConfirmOrderReq
	(*GenerateConfirmOrderRsp)(nil),                           // 1: admin.GenerateConfirmOrderRsp
	(*GenerateOrderReq)(nil),                                  // 2: admin.GenerateOrderReq
	(*GenerateOrderRsp)(nil),                                  // 3: admin.GenerateOrderRsp
	(*PaySuccessReq)(nil),                                     // 4: admin.PaySuccessReq
	(*PaySuccessRsp)(nil),                                     // 5: admin.PaySuccessRsp
	(*CancelTimeOutOrderReq)(nil),                             // 6: admin.CancelTimeOutOrderReq
	(*CancelTimeOutOrderRsp)(nil),                             // 7: admin.CancelTimeOutOrderRsp
	(*CancelOrderReq)(nil),                                    // 8: admin.CancelOrderReq
	(*CancelOrderRsp)(nil),                                    // 9: admin.CancelOrderRsp
	(*OrderListReq)(nil),                                      // 10: admin.OrderListReq
	(*OrderListRsp)(nil),                                      // 11: admin.OrderListRsp
	(*OrderDetailReq)(nil),                                    // 12: admin.OrderDetailReq
	(*OrderDetailRsp)(nil),                                    // 13: admin.OrderDetailRsp
	(*CancelUserOrderReq)(nil),                                // 14: admin.CancelUserOrderReq
	(*CancelUserOrderRsp)(nil),                                // 15: admin.CancelUserOrderRsp
	(*ConfirmReceiveOrderReq)(nil),                            // 16: admin.ConfirmReceiveOrderReq
	(*ConfirmReceiveOrderRsp)(nil),                            // 17: admin.ConfirmReceiveOrderRsp
	(*DeleteOrderReq)(nil),                                    // 18: admin.DeleteOrderReq
	(*DeleteOrderRsp)(nil),                                    // 19: admin.DeleteOrderRsp
	(*GenerateConfirmOrderRsp_CalcAmount)(nil),                // 20: admin.GenerateConfirmOrderRsp.CalcAmount
	(*GenerateConfirmOrderRsp_IntegrationConsumeSetting)(nil), // 21: admin.GenerateConfirmOrderRsp.IntegrationConsumeSetting
	(*GenerateConfirmOrderRsp_MemberReceiveAddress)(nil),      // 22: admin.GenerateConfirmOrderRsp.MemberReceiveAddress
	(*GenerateConfirmOrderRsp_CartPromotionItem)(nil),         // 23: admin.GenerateConfirmOrderRsp.CartPromotionItem
	(*GenerateConfirmOrderRsp_CouponHistoryDetail)(nil),       // 24: admin.GenerateConfirmOrderRsp.CouponHistoryDetail
}
var file_portal_order_proto_depIdxs = []int32{
	23, // 0: admin.GenerateConfirmOrderRsp.cart_promotion_items:type_name -> admin.GenerateConfirmOrderRsp.CartPromotionItem
	22, // 1: admin.GenerateConfirmOrderRsp.member_receive_address:type_name -> admin.GenerateConfirmOrderRsp.MemberReceiveAddress
	24, // 2: admin.GenerateConfirmOrderRsp.coupon_history_details:type_name -> admin.GenerateConfirmOrderRsp.CouponHistoryDetail
	21, // 3: admin.GenerateConfirmOrderRsp.integration_consume_setting:type_name -> admin.GenerateConfirmOrderRsp.IntegrationConsumeSetting
	20, // 4: admin.GenerateConfirmOrderRsp.calc_amount:type_name -> admin.GenerateConfirmOrderRsp.CalcAmount
	0,  // 5: admin.PortalOrderApi.GenerateConfirmOrder:input_type -> admin.GenerateConfirmOrderReq
	2,  // 6: admin.PortalOrderApi.GenerateOrder:input_type -> admin.GenerateOrderReq
	4,  // 7: admin.PortalOrderApi.PaySuccess:input_type -> admin.PaySuccessReq
	6,  // 8: admin.PortalOrderApi.CancelTimeOutOrder:input_type -> admin.CancelTimeOutOrderReq
	8,  // 9: admin.PortalOrderApi.CancelOrder:input_type -> admin.CancelOrderReq
	10, // 10: admin.PortalOrderApi.OrderList:input_type -> admin.OrderListReq
	12, // 11: admin.PortalOrderApi.OrderDetail:input_type -> admin.OrderDetailReq
	14, // 12: admin.PortalOrderApi.CancelUserOrder:input_type -> admin.CancelUserOrderReq
	16, // 13: admin.PortalOrderApi.ConfirmReceiveOrder:input_type -> admin.ConfirmReceiveOrderReq
	18, // 14: admin.PortalOrderApi.DeleteOrder:input_type -> admin.DeleteOrderReq
	1,  // 15: admin.PortalOrderApi.GenerateConfirmOrder:output_type -> admin.GenerateConfirmOrderRsp
	3,  // 16: admin.PortalOrderApi.GenerateOrder:output_type -> admin.GenerateOrderRsp
	5,  // 17: admin.PortalOrderApi.PaySuccess:output_type -> admin.PaySuccessRsp
	7,  // 18: admin.PortalOrderApi.CancelTimeOutOrder:output_type -> admin.CancelTimeOutOrderRsp
	9,  // 19: admin.PortalOrderApi.CancelOrder:output_type -> admin.CancelOrderRsp
	11, // 20: admin.PortalOrderApi.OrderList:output_type -> admin.OrderListRsp
	13, // 21: admin.PortalOrderApi.OrderDetail:output_type -> admin.OrderDetailRsp
	15, // 22: admin.PortalOrderApi.CancelUserOrder:output_type -> admin.CancelUserOrderRsp
	17, // 23: admin.PortalOrderApi.ConfirmReceiveOrder:output_type -> admin.ConfirmReceiveOrderRsp
	19, // 24: admin.PortalOrderApi.DeleteOrder:output_type -> admin.DeleteOrderRsp
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_portal_order_proto_init() }
func file_portal_order_proto_init() {
	if File_portal_order_proto != nil {
		return
	}
	file_portal_portal_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_portal_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaySuccessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaySuccessRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTimeOutOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTimeOutOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDetailRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelUserOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelUserOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReceiveOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmReceiveOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp_CalcAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp_IntegrationConsumeSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp_MemberReceiveAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp_CartPromotionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portal_order_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateConfirmOrderRsp_CouponHistoryDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portal_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portal_order_proto_goTypes,
		DependencyIndexes: file_portal_order_proto_depIdxs,
		MessageInfos:      file_portal_order_proto_msgTypes,
	}.Build()
	File_portal_order_proto = out.File
	file_portal_order_proto_rawDesc = nil
	file_portal_order_proto_goTypes = nil
	file_portal_order_proto_depIdxs = nil
}
